### ISSUE TITLE
Settings .ini

### ISSUE THREAD

**Issue by Nikopol89** [PieRGud/ComputerPlus#16]
Updated .ini settings for new features as "no background" and "no pause".

**Comment by PieRGud** [comment]
As I mentioned in the mod page's comment section, it would be wiser for the computer to remember pause and background toggles. I'd like to keep the .ini file as clean as possible.

**Comment by ainesophaur** [comment]
It would be easy enough to persist the toggles statically so it wouldn't
have to be persisted through the ini

**Comment by Nikopol89** [comment]
Following the idea: it could be the same for the login setting.

**Comment by ainesophaur** [comment]
Very true.. Now would we want to keep that persisted for the lifetime of
the plugin, or be realistic and track it by car? Ex if a player gets a new
vehicle, they must login again.

**Comment by ainesophaur** [comment]
Commit 2e89d5dc5f82c01601ae22631ff0611d5024e693 adds this functionality. The ShowBackground and PauseGame state is now persisted throughout the lifetime of the plugin.

**Comment by ainesophaur** [comment]
Open beta 1.3.4.1 contains the resolution for this issue. It's available on [lcpdfr.com](http://www.lcpdfr.com/files/file/11453-lspdfr-computer/)
