### ISSUE TITLE
Computer plus start in movement.

### ISSUE THREAD

**Issue by talivaan** [PieRGud/ComputerPlus#17]
Is a good mod for me is one of the indispensable but every time I push the horn and the computer turns on, I think it is unnecessary to have the computer+ turn on at 100MPH on the highway, it is somewhat annoying in my opinion. me use a key board and The key binding to open computer+ cant be changed, maybe set a option in the .ini to change the key binding can be a solution but  I would like it to return to be as before, to only activate the computer when the car is completely stopped not in movement.

**Comment by ainesophaur** [comment]
@talivaan are you interested in testing a fix? Im about to fire up GTA to try it, but it always helps to get a second confirmation.

**Comment by ainesophaur** [comment]
[ComputerPlus_bugfix_prevent_open_in_motion.zip](https://github.com/PieRGud/ComputerPlus/files/711671/ComputerPlus_bugfix_prevent_open_in_motion.zip)

The attached file is an updated DLL which puts the speed check back in. Just ran it on my machine. We probably won't push the update to the main stream for a few days (unless we get more complaints on it)

**Comment by ainesophaur** [comment]
Commit 1a33b63a313b8b43385ee60ce18ccdf8700990b5 resolves this bug

**Comment by ainesophaur** [comment]
Open beta 1.3.4.1 contains the resolution for this issue. It's available on [lcpdfr.com](http://www.lcpdfr.com/files/file/11453-lspdfr-computer/)
