### ISSUE TITLE
InvalidOperationException: Object is currently in use elsewhere.

### ISSUE THREAD

**Issue by PieRGud** [PieRGud/ComputerPlus#2]
This crash can occur while searching for peds/vehicles.

ComputerPlus has been having issues with non-thread-safe calls for a while now. It seems as though Gwen in it's current state does not have the functionality to allow thread-safe calls. If anyone has any other ideas on how this crash could be avoided, feel free to chime in!

**Attempted to fix this using SynchronizationContext. Didn't quite work.**

**Comment by Stealth22PD** [comment]
Apparently this is a bug in RPH. Will require re-testing after the release of RPH 39.

**Comment by PieRGud** [comment]
Fixed in RPH 39.
