### ISSUE TITLE
[1.3.4.4] Computer+ screen not opening

### ISSUE THREAD

**Issue by jmartini89** [piergud/ComputerPlus#25]
Using default keybinding (E) or custom (tested with Q) does not open the Computer+ screen anymore.
I'd say it's a major issue, plugin is no more usable :/

**Comment by ainesophaur** [comment]
Please attach your computerplus.ini

**Comment by Nikopol89** [comment]
Don't know how to set a spoiler here, sorry. Requested file's content follows:

[SETTINGS]
LoginName=Nikopol
LoginPass=DoNuTz
SkipLogin=true

; Try to follow the LAPD convention for the unit number (or at least keep it to 6 characters or less), thanks!!
UnitNumber=1-L-18

[KEYBINDINGS]
; Valid keys can be found @ https://msdn.microsoft.com/en-us/library/system.windows.forms.keys(v=vs.110).aspx

; Open Computer+
;
; If all options are set to None or do not exist, Computer+ will fallback to the same button
; used to open the regular LSPDFR computer

OpenComputerPlusKey=E
OpenComputerPlusModifierKey=None
OpenComputerPlusControllerButton=None
OpenComputerPlusControllerModifierButton=None

; Close Computer+ Key
;
; Please note this event will not get detected if the mouse
; is hovering over a form as the form will intercept the keypress
; and not pass it down

CloseComputerPlusKey=Back
CloseComputerPlusModifierKey=LControlKey
CloseComputerPlusControllerButton=X
CloseComputerPlusControllerModifierButton=None

; Open SimpleNotepad
;
; Please note this will only be detected while Computer+ is not open
; Inside of Computer+ is a button to open SimpleNotepad

OpenSimpleNotepadKey=PageDown
OpenSimpleNotepadModifierKey=LControlKey
OpenSimpleNotepadControllerButton=None
OpenSimpleNotepadControllerModifierButton=None


[VEHICLE BACKGROUNDS]
; LSPD
police=lspd.jpg
police2=lspd.jpg
police3=lspd.jpg
police4=lspd.jpg
police5=lspd.jpg
police41=lspd.jpg
police42=lspd.jpg
police43=lspd.jpg
police44=lspd.jpg
policet=lspd.jpg
riot=lspd.jpg
policeinsurgent=lspd.jpg
policek9=lspd.jpg

; LSIAPD
policelsia=lsia.jpg
policelsia2=lsia.jpg
policelsia3=lsia.jpg

; PAP
policeport=port.jpg
policeport2=port.jpg
policeport3=port.jpg
policeportb=port.jpg

; SAHP
hwaycar=sahp.jpg
hwaycar2=sahp.jpg
hwaycar3=sahp.jpg
hwayswatcar=sahp.jpg
policeb=sahp.jpg
policeb2=sahp.jpg

; BCSO
sheriff=bcso.jpg
sheriff2=bcso.jpg
sheriff3=bcso.jpg
sheriff4=bcso.jpg
sheriffriot=bcso.jpg
sheriffinsurgent=bcso.jpg

; LSSD
lssheriff=lssd.jpg
lssheriff2=lssd.jpg
lssheriff3=lssd.jpg
lssheriff4=lssd.jpg
sheriffriot2=lssd.jpg
sheriffinsurgent2=lssd.jpg

; NOOSE
noose=noose.jpg
noose2=noose.jpg
noose3=noose.jpg
noose4=noose.jpg
nooseriot=noose.jpg
nooseinsurgent=noose.jpg

; FIB
fbi=fib.jpg
fbi2=fib.jpg
fbi3=fib.jpg
fbi4=fib.jpg
fbiriot=fib.jpg
fbiinsurgent=fib.jpg

; SASP
pranger=sapr.jpg
pranger2=sapr.jpg
prangeratv=sapr.jpg

; USAF
usafmerit=usaf.jpg

**Comment by ainesophaur** [comment]
Are you able to open SimpleNotepad on foot?

**Comment by Nikopol89** [comment]
Yes

**Comment by ainesophaur** [comment]
Can you try setting a modifier key to open Computer+
