### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by armydragon101** [piergud/ComputerPlus#35]
So I go in game and go on-duty. I get a police car and wait for everything to load. Once everything is loaded I try to open the computer plus computer by holding E and it doesn't open. Please help!!
![1](https://user-images.githubusercontent.com/35117726/34587085-6105e300-f16c-11e7-919f-3801ce709a99.PNG)
Here's my plugins folder.

**Comment by MrFlashGame** [comment]
I think I have the same problem. When I long press E, the default police computer opens up.

**Comment by Nufflee** [comment]
I have the same problem.

**Comment by TGYuurei** [comment]
I also have the same problem, It worked perfectly fine one time, Then hasn't worked since. I've been going ape over this...

**Comment by piergud** [comment]
No one is ignoring it. I’ll look into issues with toggling. For now, try to change the computer toggle to a different key and let me know how that goes.
