### ISSUE TITLE
{ } Missing.

### ISSUE THREAD

**Issue by Alexandros-Kordatzakis** [piergud/ComputerPlus#39]
I know that it has to be intuitive, but for someone that just wants to see the example, copy-paste it and modify it, it may find a hard time resolving this...  It's not a very big issue.   The path is: ComputerPlus/API Examples/ExampleCallout/ExampleCallout.cs     at the end of the file.

**Comment by Stealth22PD** [comment]
I don't see any missing brackets?

**Comment by Alexandros-Kordatzakis** [comment]
It's from line 117...122 .   Thats your code:

**public void CleanUp()
        {
            if (blip)
                blip.Delete();
            if (driver)
                driver.Delete();
            if (vehicle)
                vehicle.Delete();
        }**

On the "if" statements there are no brackets.

https://github.com/piergud/ComputerPlus/blob/master/API%20Examples/ExampleCallout/ExampleCallout.cs

https://imgur.com/a/dOigVtn

**Comment by piergud** [comment]
It’s just syntax. When you have a single statement in a condition block, enclosing the block with brackets is optional.

**Comment by Alexandros-Kordatzakis** [comment]
Ok.
