### ISSUE TITLE
Alt-tabbing with Computer+ open locks up the game

### ISSUE THREAD

**Issue by darkmyre** [PieRGud/ComputerPlus#8]
If you open Computer+, then for some reason alt-tab out of GTA, tabbing back in and resuming the game is impossible. The Computer+ gui is still shown, but cant be interacted with (mouse or kb) presumably because the game is paused. Game cannot be unpaused because Computer+ is covering pause screen... although esc key also doesnt work, making the game essentially locked paused.

**Comment by Albo1125** [comment]
This doesn't happen for me.
Have you tried disabling AutoPause on game focus loss from your GTA settings?

**Comment by PieRGud** [comment]
This is an issue with Gwen forms and pause on focus loss. Pressing Esc right after coming back from an Alt + Tab should work. Alternatively, you can just turn off pause game on focus loss like Albo suggested.
